# Default values for hello-world.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: "hello-world"
  # Overrides the image tag whose default is the chart appVersion.
  tag: "1.0"
  pullPolicy: IfNotPresent

service:
  type: NodePort
  port: 80
